
DROP DATABASE news;
CREATE DATABASE news;
USE news;

CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(20) NOT NULL,
	name VARCHAR(30) NOT NULL,
	last_name VARCHAR(30) NOT NULL,
	password CHAR(32) NOT NULL
);

CREATE TABLE news (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(200) NOT NULL,
	created_at TIMESTAMP NOT NULL,
	body TEXT NOT NULL,
	user_id INT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id)
);
